# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_livro_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comentario',
            name='livro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Livro'),
            preserve_default=False,
        ),
    ]
