# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20151203_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='titulo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
